name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout da base de código
        uses: actions/checkout@v3.5.3
      - name: Autenticação no Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Construindo a imagem da aplicação
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            itdaniloamaral/rotten-potatoes:${{github.run_number}}
            itdaniloamaral/rotten-potatoes:latest
            
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps: 
      - name: Checkout da base de código
        uses: actions/checkout@v3.5.3
      - name: Configurar as credenciais de acesso
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Configuração do Kubeconfig
        shell: bash
        run: |
          aws eks update-kubeconfig --name eks-imersao --region us-east-1
      - name: Deploy do MongoDB no cluster Kubernetes 
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            k8s-deploy/01-mongo/deployment.yaml

      - name: Deploy da aplicação no cluster Kubernetes
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            k8s-deploy/02-myapp/deployment.yaml
          images: |
            itdaniloamaral/rotten-potatoes:${{github.run_number}}
